### ISSUE TITLE
Cute to-do app!

### ISSUE THREAD

**Issue by jokosanyang** [FAC-Sixteen/Week-2-project-JASH#22]
I like the styling of your app. The crosses for delete and checkbox for done are very intuitive.

For a little bonus profesh touch, have you considered adding a favicon and title for the tab/page?

**Comment by tloth** [comment]
Thanks, boo! Favicon and more aesthetically pleasing title added.
![done](https://media1.giphy.com/media/py2UYwTIX5SXm/giphy.gif)
