### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by aniablaziak** [FAC-Sixteen/Week-2-project-JASH#26]
You could remove console.log() and unneeded commented code from dom.js and test.js to make the code more readable and clean.
Maybe you could consider storing you "experimental" code in a different branch?
![cleaning](https://media.giphy.com/media/dJEMs13SrsiuA/giphy.gif)

**Comment by jameslevine** [comment]
We have commented out the code because it is useful for us to talk about in the presentation to log our thought process!

Sorry about the mess!
