### ISSUE TITLE
Liking how your tests have subtests

### ISSUE THREAD

**Issue by dubhcait** [FAC-Sixteen/Week-2-project-JASH#27]
![](https://media.giphy.com/media/2w6KRYh2YXHUJapKUP/giphy.gif)

It's interesting how you have two subtests running at the same time (equal and deepEqual)! 😎

I didn't even think to do that

Especially the tests you decided to group, very logical

**Comment by bobbysebolao** [comment]
Agreed. And I think I understand deepEqual() now!

![](https://media.giphy.com/media/Lcn0yF1RcLANG/giphy.gif)
