### ISSUE TITLE
.filter doesn't change the original argument

### ISSUE THREAD

**Issue by aterna01** [FAC-Sixteen/Week-2-project-JASH#28]
You made a copy of the original array before used .filter . You do not have to do that ,filter method does not modify original input. 

       deleteTodo: function(todos, idToDelete) {
           let newObj = todoFunctions.cloneArrayOfObjects(todos);
           return newObj.filter(todo => todo.id !== idToDelete);
       },

Try: 

    deleteTodo: function(todos, idToDelete) {

      return todos.filter(todo => todo.id !== idToDelete);
       
    },

**Comment by tloth** [comment]
thanks!
![filter](https://thumbs.gfycat.com/PeriodicDimpledIggypops-size_restricted.gif)
